server:
  port: 8888
spring:
  profiles:
    active: docker
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linuxmaniaco/ProjConfigRepoInfnet
          clone-on-start: true
          search-paths:
            - "config"
          username: linuxmaniaco

          default-label: master